# Generated by Django 3.2.3 on 2021-06-02 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='modifier',
            field=models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='modifier_id',
            field=models.CharField(blank=True, help_text='修改人Id', max_length=255, null=True, verbose_name='修改人Id'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='modifier',
            field=models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='modifier_id',
            field=models.CharField(blank=True, help_text='修改人Id', max_length=255, null=True, verbose_name='修改人Id'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='modifier',
            field=models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='modifier_id',
            field=models.CharField(blank=True, help_text='修改人Id', max_length=255, null=True, verbose_name='修改人Id'),
        ),
        migrations.AlterField(
            model_name='menupermission',
            name='menu',
            field=models.ForeignKey(db_constraint=False, help_text='关联菜单', on_delete=django.db.models.deletion.CASCADE, to='system.menu', verbose_name='关联菜单'),
        ),
        migrations.AlterField(
            model_name='menupermission',
            name='modifier',
            field=models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='menupermission',
            name='modifier_id',
            field=models.CharField(blank=True, help_text='修改人Id', max_length=255, null=True, verbose_name='修改人Id'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='modifier',
            field=models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='modifier_id',
            field=models.CharField(blank=True, help_text='修改人Id', max_length=255, null=True, verbose_name='修改人Id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modifier',
            field=models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modifier_id',
            field=models.CharField(blank=True, help_text='修改人Id', max_length=255, null=True, verbose_name='修改人Id'),
        ),
        migrations.AlterField(
            model_name='role',
            name='modifier',
            field=models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='role',
            name='modifier_id',
            field=models.CharField(blank=True, help_text='修改人Id', max_length=255, null=True, verbose_name='修改人Id'),
        ),
        migrations.AlterField(
            model_name='sysdictionarylist',
            name='modifier',
            field=models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='sysdictionarylist',
            name='modifier_id',
            field=models.CharField(blank=True, help_text='修改人Id', max_length=255, null=True, verbose_name='修改人Id'),
        ),
        migrations.AlterField(
            model_name='users',
            name='modifier',
            field=models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='users',
            name='modifier_id',
            field=models.CharField(blank=True, help_text='修改人Id', max_length=255, null=True, verbose_name='修改人Id'),
        ),
    ]
