# Generated by Django 3.2.3 on 2021-06-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20210602_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='modifier_id',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='modifier_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='modifier_id',
        ),
        migrations.RemoveField(
            model_name='menupermission',
            name='modifier_id',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='modifier_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modifier_id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='modifier_id',
        ),
        migrations.RemoveField(
            model_name='sysdictionarylist',
            name='modifier_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='modifier_id',
        ),
    ]
