# Generated by Django 3.2.3 on 2021-06-04 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20210602_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupermission',
            name='menu',
            field=models.ForeignKey(db_constraint=False, help_text='关联菜单', on_delete=django.db.models.deletion.CASCADE, related_name='menuPermission', to='system.menu', verbose_name='关联菜单'),
        ),
    ]
