# Generated by Django 3.2.3 on 2021-06-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_menupermission_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='dept',
            field=models.ManyToManyField(db_constraint=False, help_text='数据权限-关联部门', to='system.Dept', verbose_name='数据权限-关联部门'),
        ),
        migrations.AlterModelTable(
            name='menupermission',
            table='system_menu_button',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='system_button',
        ),
    ]
