# Generated by Django 3.2.3 on 2021-06-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20210605_0136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='Button',
        ),
        migrations.RenameModel(
            old_name='MenuPermission',
            new_name='MenuButton',
        ),
    ]
