# Generated by Django 3.2.3 on 2021-06-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20210605_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(db_constraint=False, help_text='关联菜单的接口按钮', to='system.MenuButton', verbose_name='关联菜单的接口按钮'),
        ),
    ]
